/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chisami' at '2016/8/17 上午 12:42' with Gradle 2.14
 *
 * @author chisami, @date 2016/8/17 上午 12:42
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
